services:
  backend:
    build: ./backend
    container_name: sip-backend
    network_mode: host
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: sip-frontend
    network_mode: host
    restart: unless-stopped
